#!/bin/bash
sudo apt install wget
MANIFEST=git://github.com/StagOS/manifest.git
BRANCH=r11

mkdir -p /tmp/rom
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice.Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init --no-repo-verify --depth=1 -u "$MANIFEST" -b "$BRANCH" -g default,-device,-mips,-darwin,-notdefault
git config --global user.name "Box In A Box"
git config --global user.email evanferrao@gmail.com

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all) || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8

git clone https://github.com/kardebayan/device_oppo_CPH1859.git device/oppo/CPH1859
git clone https://github.com/kardebayan/vendor_oppo_CPH1859.git vendor/oppo/CPH1859
git clone https://github.com/kardebayan/android_kernel_oppo_mt6771.git kernel/oppo/mt6771
git clone https://github.com/CPH1859/prebuilt_clang-6.0.2 prebuilts/clang/host/linux-x86/clang-r316199
rm -rf vendor/nxp
rm -rf device/mediatek/sepolicy && git clone https://github.com/bluelytning/device_mediatek_sepolicy.git device/mediatek/sepolicy
